kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-expense
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-038e7013a083f6d07
  directoryPerms: "700"
  basePath: "/expense" # optional
  