apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    project: expense
    module: backend
    environment: dev
  ports:
  - name: nginx-service-port
    protocol: TCP
    port: 80   # Service Port
    targetPort: 80 # Container port