apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:  # These are Replicaset labels
    app: nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:  # These are used to select the pod to create replicas
      tier: frontend
      app: nginx
  # This is pod defination    
  template:
    metadata:
      labels:    # These labels belong to pod
        tier: frontend
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    tier: frontend
    app: nginx
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80   # service port
    targetPort: 80  # container port
