apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:  # These are Replicaset labels
    app: nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:  # These are used to select the pod to create replicas
      tier: frontend
      app: nginx
  # This is pod defination    
  template:
    metadata:
      labels:    # These labels belong to pod
        tier: frontend
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
